Convert "Cordova_media_capture" into a dune library
besport/ocaml-cordova-plugin-media-capture pull request #1
Opened 2021-07-28 08:16 UTC by Thibaut-Gudin

2021-07-28 08:18 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Il faut une dépendance sur dune.

2021-07-28 08:18 UTC, Thibaut-Gudin commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
En effet je m'en occupe.

2021-07-28 08:23 UTC, Thibaut-Gudin commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
> Il faut une dépendance sur dune.

Attendez, que voulez vous dire par une dépendance sur dune?
Je n'ai pas souvenir avoir jamais mis "dune" dans le ".opam" d'aucune de mes autres librairies et pourtant elles semblent fonctionner.

2021-07-28 08:36 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Ça marche comme dune est installé chez toi. Si par contre quelqu'un veut installer le paquet via opam sans avoir installé dune, ça échoue.

2021-07-28 08:37 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Tu peux mettre `"dune" {>= "2.7"}`.

2021-07-28 08:39 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Tu peux ajouter cette dépendance à tous tes paquets (qui utilisent dune).

2021-07-28 08:40 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Ce sera nécessaire au plus tard quand on les publie sur opam.

2021-07-28 09:04 UTC, Thibaut-Gudin commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Ce sera fait, ce sera sans doute push un peu plus tard, tous les "build" ont échoués: il semblerait que la construction de la librairie est a revoir, je pusherait tout en même temps.

2021-07-28 09:11 UTC, jrochel commented on cordova-plugin-media-capture.opam
>    "gen_js_api"
Les erreurs de compilation sont informatives : https://github.com/besport/ocaml-cordova-plugin-media-capture/pull/1/checks?check_run_id=3179912245

2021-09-10 08:33 UTC, jrochel requested changes

2021-09-10 08:33 UTC, jrochel commented on cordova-plugin-media-capture.opam
> +version:      "1.0"
Est-ce que tu pourrais passer à version 2.0 ?

2021-09-10 08:34 UTC, jrochel commented on cordova-plugin-media-capture.opam
> +version:      "1.0"
En fait non, laisse tomber.

2021-09-10 08:34 UTC, merged